import placeholder from "../src/assets/images/placeholder.avif";

const products = [
  {
    id: 0,
    name: "Cowboy Boots",
    price: 76,
    category: "Clothing",
    src: placeholder,
  },
  {
    id: 1,
    name: "Baseball Cap",
    price: 24,
    category: "Assessories",
    src: placeholder,
  },
  {
    id: 2,
    name: "Gloves",
    price: 16,
    category: "Assessories",
    src: placeholder,
  },
  {
    id: 3,
    name: "Sneakers",
    price: 67,
    category: "Clothing",
    src: placeholder,
  },
  {
    id: 4,
    name: "Sunglasses",
    price: 20,
    category: "Assessories",
    src: placeholder,
  },
  {
    id: 5,
    name: "Beanie",
    price: 17,
    category: "Accessories",
    src: placeholder,
  },
  {
    id: 6,
    name: "Necklace",
    price: 26,
    category: "Assessories",
    src: placeholder,
  },
  {
    id: 7,
    name: "Earrings",
    price: 21,
    category: "Assessories",
    src: placeholder,
  },
  {
    id: 8,
    name: "Hoodie",
    price: 54,
    category: "Clothing",
    src: placeholder,
  },
  {
    id: 9,
    name: "Sunscreen",
    price: 24,
    category: "Skincare",
    src: placeholder,
  },
  {
    id: 10,
    name: "Eyeshadow",
    price: 34,
    category: "Makeup",
    src: placeholder,
  },
  {
    id: 11,
    name: "Blush",
    price: 21,
    category: "Makeup",
    src: placeholder,
  },
  {
    id: 12,
    name: "Clock",
    price: 22,
    category: "Decor",
    src: placeholder,
  },
  {
    id: 13,
    name: "Cleanser",
    price: 19,
    category: "Skincare",
    src: placeholder,
  },
  {
    id: 14,
    name: "Poster",
    price: 12,
    category: "Decor",
    src: placeholder,
  },
  {
    id: 15,
    name: "Hydrating Cream",
    price: 54,
    category: "Skincare",
    src: placeholder,
  },
  {
    id: 16,
    name: "Lip Oil",
    price: 10,
    category: "Makeup",
    src: placeholder,
  },
  {
    id: 17,
    name: "Face Mask",
    price: 5,
    category: "Skincare",
    src: placeholder,
  },
  {
    id: 18,
    name: "Plant",
    price: 13,
    category: "Decor",
    src: placeholder,
  },
  {
    id: 19,
    name: "Bronzer",
    price: 24,
    category: "Makeup",
    src: placeholder,
  },
  {
    id: 20,
    name: "Retinol Cream",
    price: 47,
    category: "Skincare",
    src: placeholder,
  },
  {
    id: 21,
    name: "Lipstick",
    price: 22,
    category: "Makeup",
    src: placeholder,
  },
];

export default products;
